spring:
  profiles:
    active: dev
mybatis:
  type-aliases-package: cn.anshirui.store.appdevelop.entity

# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

