server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /appject

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anshirui?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 100
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 10000
      ## 连接池母子
      pool-name: DatebookHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-init-sql: SELECT 1
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空)
    password:
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 10
        ## 连接池中的最小空闲连接
        min-idle: 0
      ## 连关闭超时时间（毫秒）
      shutdown-timeout: 5000

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    listener:
#      ##并发消费者的初始化值
#      concurrency: 10
#      ##并发消费者的最大值
#      max-concurrency: 20
#      ##每个消费者每次监听时可拉取处理的消息数量
#      prefetch: 5
    connection-timeout: 15000
#    # 开启发送确认
#    publisher-confirms: true
#    # 开启发送失败退回
#    publisher-returns: true
#    # 开启ACK
#    listener:
#      direct:
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual

logging:
  config: classpath:log/logback-spring.xml



